#!/bin/bash

#for var in ${!SERF*}; do echo ${var}=${!var};done

# ask
serf members -status=alive | while read line ;do
  NEXT_HOST=$(echo $line|cut -d' ' -f 1)
  NEXT_SHORT=${NEXT_HOST%%.*}
  NEXT_ADDR=$(echo $line|cut -d' ' -f 2)
  NEXT_IP=${NEXT_ADDR%%:*}
  echo address=\"/$NEXT_HOST/$NEXT_SHORT/$NEXT_IP\"
done > /etc/dnsmasq.d/0hosts

service dnsmasq restart
